//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::auth_grant::Entity as AuthGrant;
pub use super::auth_token::Entity as AuthToken;
pub use super::passport::Entity as Passport;
pub use super::user::Entity as User;
